import type { Plugin } from 'vite-plus'
import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { loadEnv } from 'vite-plus'

export const RARI_TYPES_DIR = path.join('node_modules', '.rari', 'types')
export const RARI_ENV_DTS = 'env.d.ts'

const ENV_FILE_NAMES = [
  '.env',
  '.env.local',
  '.env.development',
  '.env.development.local',
  '.env.production',
  '.env.production.local',
  '.env.test',
  '.env.test.local',
  '.env.example',
] as const

const VITE_ENV_KEY_LINE_RE = /^\s*(?:export\s+)?(VITE_[A-Z0-9_]+)\s*=/gm

export function rariTypesDir(projectRoot: string): string {
  return path.join(projectRoot, RARI_TYPES_DIR)
}

export function rariEnvDtsPath(projectRoot: string): string {
  return path.join(rariTypesDir(projectRoot), RARI_ENV_DTS)
}

export function parseViteEnvKeysFromSource(source: string): string[] {
  const keys = new Set<string>()
  VITE_ENV_KEY_LINE_RE.lastIndex = 0
  for (const match of source.matchAll(VITE_ENV_KEY_LINE_RE)) {
    keys.add(match[1])
  }
  return [...keys]
}

function collectKeysFromEnvFiles(projectRoot: string): Set<string> {
  const keys = new Set<string>()
  for (const name of ENV_FILE_NAMES) {
    const filePath = path.join(projectRoot, name)
    if (!fs.existsSync(filePath)) continue
    try {
      for (const key of parseViteEnvKeysFromSource(fs.readFileSync(filePath, 'utf8'))) {
        keys.add(key)
      }
    } catch {
      // ignore unreadable env files
    }
  }
  return keys
}

export function collectViteEnvKeys(projectRoot: string, mode: string): string[] {
  const keys = collectKeysFromEnvFiles(projectRoot)
  for (const key of Object.keys(loadEnv(mode, projectRoot, 'VITE_'))) {
    if (key.startsWith('VITE_')) keys.add(key)
  }
  return [...keys].sort()
}

export function renderEnvDts(keys: readonly string[]): string {
  const header = '// Generated by rari. Do not edit.\n'
  if (keys.length === 0) {
    return `${header}// No VITE_* keys found in .env* files.\nexport {}\n`
  }
  const fields = keys.map(key => `  readonly ${key}?: string`).join('\n')
  return `${header}interface ImportMetaEnv {\n${fields}\n}\n`
}

export function emitRariEnvTypes(projectRoot: string, mode: string): string {
  const outDir = rariTypesDir(projectRoot)
  fs.mkdirSync(outDir, { recursive: true })
  const outFile = rariEnvDtsPath(projectRoot)
  const content = renderEnvDts(collectViteEnvKeys(projectRoot, mode))
  if (fs.existsSync(outFile) && fs.readFileSync(outFile, 'utf8') === content) return outFile
  fs.writeFileSync(outFile, content)
  return outFile
}

function isEnvWatchPath(filePath: string): boolean {
  const base = path.basename(filePath)
  return base === '.env' || base.startsWith('.env.')
}

export function createEnvTypesPlugin(projectRoot?: string): Plugin {
  let root = projectRoot != null && projectRoot !== '' ? path.resolve(projectRoot) : process.cwd()
  let mode = 'development'

  return {
    name: 'rari:env-types',
    configResolved(config) {
      root = path.resolve(projectRoot != null && projectRoot !== '' ? projectRoot : config.root)
      mode = config.mode
      emitRariEnvTypes(root, mode)
    },
    buildStart() {
      emitRariEnvTypes(root, mode)
    },
    configureServer(server) {
      emitRariEnvTypes(root, mode)
      const envGlobs = ENV_FILE_NAMES.map(name => path.join(root, name))
      server.watcher.add(envGlobs)
      const refresh = (file: string) => {
        if (isEnvWatchPath(file)) emitRariEnvTypes(root, mode)
      }
      server.watcher.on('change', refresh)
      server.watcher.on('add', refresh)
      server.watcher.on('unlink', refresh)
    },
  }
}
