catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
packages:
  - examples/*
  - packages/*
  - '!packages/rari-darwin-x64'
  - '!packages/rari-linux-arm64'
  - '!packages/rari-linux-x64'
  - '!packages/rari-win32-x64'
  - web
catalogs:
  analytics:
    '@posthog/react': ^1.8.1
    posthog-js: ^1.354.1
  build:
    rolldown: 1.0.0-rc.5
    rolldown-vite: ^7.3.1
    tsdown: ^0.20.3
  cli:
    '@clack/prompts': ^1.0.1
  default:
    rari: ^0.10.8
  eslint:
    '@antfu/eslint-config': ^7.6.1
    '@e18e/eslint-plugin': ^0.2.0
    '@eslint-react/eslint-plugin': ^2.13.0
    '@typescript-eslint/utils': ^8.56.1
    eslint: ^10.0.2
    eslint-plugin-de-morgan: ^2.0.0
    eslint-plugin-oxlint: ^1.50.0
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.5.2
    knip: ^5.85.0
    oxlint: ^1.50.0
  mdx:
    '@mdx-js/mdx': 3.1.1
    '@shikijs/core': ^3.23.0
    '@shikijs/engine-oniguruma': ^3.23.0
    '@shikijs/langs': ^3.23.0
    '@shikijs/themes': ^3.23.0
    '@shikijs/types': ^3.23.0
    remark-gfm: ^4.0.1
  monitoring:
    '@sentry/react': ^10.40.0
  react:
    '@types/react': ^19.2.14
    '@types/react-dom': ^19.2.3
    react: ^19.2.4
    react-dom: ^19.2.4
  tailwind:
    '@tailwindcss/vite': ^4.2.1
    tailwindcss: ^4.2.1
  testing:
    '@playwright/test': ^1.58.2
    '@vitest/coverage-v8': 4.0.18
    vitest: ^4.0.18
  typescript:
    '@types/node': ^25.3.0
    '@typescript/native-preview': ^7.0.0-dev.20260225.1
  utils:
    unist-util-visit: ^5.1.0
onlyBuiltDependencies:
  - esbuild
  - oxlint
  - '@shikijs/engine-oniguruma'
