catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1

packages:
  - examples/*
  - packages/*
  - web
catalogs:
  analytics:
    '@posthog/react': ^1.7.0
    posthog-js: ^1.335.3
  build:
    esbuild: ^0.27.2
    rolldown-vite: ^7.3.1
    tsdown: ^0.20.1
  cli:
    '@clack/prompts': ^0.11.0
  default:
    '@sentry/react': ^10.37.0
    '@types/node': ^25.0.10
    '@typescript/native-preview': ^7.0.0-dev.20260126.1
    oxlint: ^1.42.0
    rari: ^0.7.14
  eslint:
    '@antfu/eslint-config': ^7.2.0
    '@eslint-react/eslint-plugin': ^2.7.4
    eslint: ^9.39.2
    eslint-plugin-oxlint: ^1.42.0
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.26
    knip: ^5.82.1
  mdx:
    '@mdx-js/mdx': 3.1.1
    '@shikijs/core': ^3.21.0
    '@shikijs/engine-oniguruma': ^3.21.0
    '@shikijs/langs': ^3.21.0
    '@shikijs/themes': ^3.21.0
  react:
    '@types/react': ^19.2.9
    '@types/react-dom': ^19.2.3
    react: ^19.2.4
    react-dom: ^19.2.4
  tailwind:
    '@tailwindcss/vite': ^4.1.18
    tailwindcss: ^4.1.18
  utils:
    unist-util-visit: ^5.1.0
onlyBuiltDependencies:
  - esbuild
  - oxlint
  - '@shikijs/engine-oniguruma'
