catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
packages:
  - examples/*
  - packages/*
  - web
catalogs:
  analytics:
    '@posthog/react': ^1.7.0
    posthog-js: ^1.341.0
  build:
    rolldown: 1.0.0-rc.2
    rolldown-vite: ^7.3.1
    tsdown: ^0.20.1
  cli:
    '@clack/prompts': ^1.0.0
  default:
    rari: ^0.8.10
  eslint:
    '@antfu/eslint-config': ^7.2.0
    '@e18e/eslint-plugin': ^0.1.4
    '@eslint-react/eslint-plugin': ^2.9.4
    '@typescript-eslint/utils': ^8.54.0
    eslint: ^9.39.2
    eslint-plugin-de-morgan: ^2.0.0
    eslint-plugin-oxlint: ^1.43.0
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.5.0
    knip: ^5.83.0
    oxlint: ^1.43.0
  mdx:
    '@mdx-js/mdx': 3.1.1
    '@shikijs/core': ^3.22.0
    '@shikijs/engine-oniguruma': ^3.22.0
    '@shikijs/langs': ^3.22.0
    '@shikijs/themes': ^3.22.0
  monitoring:
    '@sentry/react': ^10.38.0
  react:
    '@types/react': ^19.2.11
    '@types/react-dom': ^19.2.3
    react: ^19.2.4
    react-dom: ^19.2.4
  tailwind:
    '@tailwindcss/vite': ^4.1.18
    tailwindcss: ^4.1.18
  testing:
    '@vitest/coverage-v8': 4.0.18
    vitest: ^4.0.18
  typescript:
    '@types/node': ^25.2.0
    '@typescript/native-preview': ^7.0.0-dev.20260204.1
  utils:
    unist-util-visit: ^5.1.0
onlyBuiltDependencies:
  - esbuild
  - oxlint
  - '@shikijs/engine-oniguruma'
