use std::env;
use std::fmt::Write;
use std::path::Path;
use std::path::PathBuf;

use deno_ast::MediaType;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR not set"));
    let output_path = out_dir.join("deno_node_lazy_sources.rs");

    generate_lazy_sources(&output_path);
}

fn generate_lazy_sources(output_path: &Path) {
    let ext = deno_node::deno_node::lazy_init::<
        SnapshotNpmPackageChecker,
        SnapshotNpmPackageFolderResolver,
        sys_traits::impls::RealSys,
    >();

    let mut esm_entries = String::new();
    let mut js_entries = String::new();

    for file in ext.lazy_loaded_esm_files.iter() {
        let source = file.load().unwrap_or_else(|e| {
            panic!("Failed to load lazy ESM file '{}': {}", file.specifier, e);
        });
        let source = maybe_transpile(file.specifier, &source);
        let escaped = escape_string_for_rust(&source);
        writeln!(esm_entries, "    (\"{}\", r###\"{}\"###),", file.specifier, escaped)
            .expect("Failed to write ESM entry");
    }

    for file in ext.lazy_loaded_js_files.iter() {
        let source = file.load().unwrap_or_else(|e| {
            panic!("Failed to load lazy JS file '{}': {}", file.specifier, e);
        });
        let source = maybe_transpile(file.specifier, &source);
        let escaped = escape_string_for_rust(&source);
        writeln!(js_entries, "    (\"{}\", r###\"{}\"###),", file.specifier, escaped)
            .expect("Failed to write JS entry");
    }

    let generated = format!(
        "// Auto-generated by build.rs - do not edit\n\
         // deno_node lazy-loaded sources, transpiled and embedded at compile time\n\n\
         pub static DENO_NODE_LAZY_ESM_SOURCES: &[(&str, &str)] = &[\n\
         {esm_entries}];\n\n\
         pub static DENO_NODE_LAZY_JS_SOURCES: &[(&str, &str)] = &[\n\
         {js_entries}];\n"
    );

    std::fs::write(output_path, generated).expect("Failed to write generated lazy sources");
}

fn maybe_transpile(specifier: &str, source: &str) -> String {
    let media_type = if specifier.starts_with("node:") {
        MediaType::TypeScript
    } else {
        MediaType::from_path(Path::new(specifier))
    };

    match media_type {
        MediaType::TypeScript | MediaType::Tsx | MediaType::Jsx => {}
        _ => return source.to_string(),
    }

    let specifier_url = url::Url::parse(specifier).unwrap_or_else(|_| {
        url::Url::parse(&format!("file:///{specifier}")).expect("invalid specifier")
    });

    let parsed = deno_ast::parse_module(deno_ast::ParseParams {
        specifier: specifier_url,
        text: source.into(),
        media_type,
        capture_tokens: false,
        scope_analysis: false,
        maybe_syntax: None,
    })
    .unwrap_or_else(|e| panic!("Failed to parse '{}': {}", specifier, e));

    parsed
        .transpile(
            &deno_ast::TranspileOptions {
                imports_not_used_as_values: deno_ast::ImportsNotUsedAsValues::Remove,
                ..Default::default()
            },
            &deno_ast::TranspileModuleOptions::default(),
            &deno_ast::EmitOptions {
                source_map: deno_ast::SourceMapOption::None,
                ..Default::default()
            },
        )
        .unwrap_or_else(|e| panic!("Failed to transpile '{}': {}", specifier, e))
        .into_source()
        .text
}

#[allow(clippy::disallowed_methods)]
fn escape_string_for_rust(s: &str) -> String {
    s.replace("\"###", "\"####")
}

struct SnapshotNpmPackageChecker;
impl node_resolver::InNpmPackageChecker for SnapshotNpmPackageChecker {
    fn in_npm_package(&self, _specifier: &url::Url) -> bool {
        false
    }
}

struct SnapshotNpmPackageFolderResolver;
impl node_resolver::NpmPackageFolderResolver for SnapshotNpmPackageFolderResolver {
    fn resolve_package_folder_from_package(
        &self,
        _specifier: &str,
        _referrer: &node_resolver::UrlOrPathRef,
    ) -> Result<PathBuf, node_resolver::errors::PackageFolderResolveError> {
        unimplemented!()
    }

    fn resolve_types_package_folder(
        &self,
        _types_package_name: &str,
        _maybe_package_version: Option<&deno_semver::Version>,
        _maybe_referrer: Option<&node_resolver::UrlOrPathRef>,
    ) -> Option<PathBuf> {
        None
    }
}
