import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: {
    'index': 'src/index.ts',
    'client': 'src/client.ts',
    'vite': 'src/vite.ts',
    'cli': 'src/cli.ts',
    'platform': 'src/platform.ts',
    'image/index': 'src/image/index.ts',
    'og/index': 'src/og/index.ts',
    'mdx': 'src/mdx.ts',
    'runtime/actions': 'src/runtime/actions.ts',
    'runtime/entry-client': 'src/runtime/entry-client.ts',
    'runtime/react-server-dom-rari-client': 'src/runtime/react-server-dom-rari-client.ts',
    'runtime/react-server-dom-shim': 'src/runtime/react-server-dom-shim.ts',
    'runtime/rsc-client-runtime': 'src/runtime/rsc-client-runtime.ts',
    'proxy/runtime-executor': 'src/proxy/runtime-executor.ts',
  },
  dts: true,
  format: 'esm',
  minify: true,
  external: [
    'lightningcss',
    'postcss',
    'rolldown-vite',
    '@oxc-project/types',
    'rolldown',
    '@rolldown/pluginutils',
    'virtual:app-router-provider',
    'virtual:app-router-provider.tsx',
    'virtual:react-server-dom-rari-client.ts',
    'virtual:rsc-integration.ts',
    'rari/client',
  ],
})
