import { defineConfig } from 'vite-plus'

export default defineConfig({
  pack: {
    entry: {
      'index': 'src/index.ts',
      'client': 'src/client.ts',
      'router': 'src/router.ts',
      'vite': 'src/vite.ts',
      'cli': 'src/cli.ts',
      'platform': 'src/platform.ts',
      'image/index': 'src/image/index.ts',
      'og/index': 'src/og/index.ts',
      'mdx': 'src/mdx.ts',
      'headers': 'src/headers.ts',
      'runtime/actions': 'src/runtime/actions.ts',
      'runtime/entry-client': 'src/runtime/entry-client.ts',
      'runtime/react-server-dom-shim': 'src/runtime/react-server-dom-shim.ts',
      'runtime/rsc-client-runtime': 'src/runtime/rsc-client-runtime.ts',
      'runtime/AppRouterProvider': 'src/runtime/AppRouterProvider.tsx',
      'runtime/LoadingErrorBoundary': 'src/runtime/LoadingErrorBoundary.tsx',
      'runtime/ErrorBoundaryWrapper': 'src/runtime/ErrorBoundaryWrapper.tsx',
      'runtime/vendor/react-flight-client/index': 'src/runtime/vendor/react-flight-client/index.ts',
      'runtime/vendor/react-flight-client/ReactFlightClient': 'src/runtime/vendor/react-flight-client/ReactFlightClient.ts',
      'runtime/vendor/react-flight-client/ReactFlightClientConfig': 'src/runtime/vendor/react-flight-client/ReactFlightClientConfig.ts',
      'proxy/runtime-executor': 'src/proxy/runtime-executor.ts',
      'proxy/RariRequest': 'src/proxy/RariRequest.ts',
      'proxy/RariResponse': 'src/proxy/RariResponse.ts',
    },
    minify: true,
    deps: {
      neverBundle: [
        'lightningcss',
        'postcss',
        'vite',
        'vite-plus',
        'vitest',
        '@vitest/browser',
        '@vitest/expect',
        '@vitest/runner',
        '@voidzero-dev/vite-plus-test',
        '@voidzero-dev/vite-plus-core',
        'rolldown',
        '@rolldown/pluginutils',
        '@oxc-project/types',
        'virtual:app-router-provider',
        'virtual:app-router-provider.tsx',
        'virtual:react-flight-client',
        'virtual:react-flight-client.ts',
        'virtual:rsc-integration.ts',
        'rari/client',
        'rari/router',
      ],
    },
  },
})
