avoid-breaking-exported-api = false
disallowed-types = [
  { path = "std::collections::HashMap", reason = "Use `rustc_hash::FxHashMap` instead, which is typically faster for most use cases." },
  { path = "std::collections::HashSet", reason = "Use `rustc_hash::FxHashSet` instead, which is typically faster for most use cases." },
  { path = "std::collections::BTreeMap", reason = "Use `rustc_hash::FxHashMap` instead, which is typically faster for most use cases." },
]
disallowed-methods = [
  { path = "str::to_ascii_lowercase", reason = "To avoid unecessary allocation, use `cow_utils::CowUtils::cow_to_ascii_lowercase` instead." },
  { path = "str::to_ascii_uppercase", reason = "To avoid unecessary allocation, use `cow_utils::CowUtils::cow_to_ascii_uppercase` instead." },
  { path = "str::to_lowercase", reason = "To avoid unecessary allocation, use `cow_utils::CowUtils::cow_to_lowercase` instead." },
  { path = "str::to_uppercase", reason = "To avoid unecessary allocation, use `cow_utils::CowUtils::cow_to_uppercase` instead." },
  { path = "str::replace", reason = "To avoid unecessary allocation, use `cow_utils::CowUtils::cow_replace` instead." },
  { path = "str::replacen", reason = "To avoid unecessary allocation, use `cow_utils::CowUtils::cow_replacen` instead." },
]
