use std::fmt::Write;
use std::path::PathBuf;
use std::rc::Rc;

use deno_core::{ModuleCodeString, ModuleName, SourceMapData};
use deno_error::JsErrorBox;
use rustc_hash::FxHashSet;

type Transpiler = dyn Fn(
    ModuleName,
    ModuleCodeString,
) -> Result<(ModuleCodeString, Option<SourceMapData>), JsErrorBox>;

fn main() {
    let output_dir = std::env::args()
        .nth(1)
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("crates/rari/snapshots"));

    std::fs::create_dir_all(&output_dir).expect("Failed to create output directory");

    let snapshot_path = output_dir.join("RARI_SNAPSHOT.bin");
    let residual_path = output_dir.join("residual_lazy_sources.rs");

    println!("Building V8 snapshot...");

    let ext_options = rari::runtime::ext::ExtensionOptions::default();
    let extensions = rari::runtime::ext::extensions(&ext_options, false);

    let transpiler: Rc<Transpiler> = Rc::new(|name, source| {
        rari::runtime::utils::transpile::maybe_transpile_source(name, source)
    });

    let output = deno_core::snapshot::create_snapshot(
        deno_core::snapshot::CreateSnapshotOptions {
            cargo_manifest_dir: env!("CARGO_MANIFEST_DIR"),
            startup_snapshot: None,
            skip_op_registration: false,
            extensions,
            extension_transpiler: Some(transpiler),
            with_runtime_cb: None,
        },
        None,
    )
    .expect("Failed to create V8 snapshot");

    std::fs::write(&snapshot_path, &output.output).expect("Failed to write snapshot file");
    println!(
        "Snapshot written to {} ({:.2} MB)",
        snapshot_path.display(),
        output.output.len() as f64 / 1024.0 / 1024.0
    );

    let consumed: FxHashSet<&str> =
        output.consumed_lazy_specifiers.iter().map(|s| s.as_str()).collect();

    println!("Consumed {} lazy specifiers during snapshot creation", consumed.len());

    let ext_options = rari::runtime::ext::ExtensionOptions::default();
    let extensions = rari::runtime::ext::extensions(&ext_options, false);

    let mut residual_esm = Vec::new();
    let mut residual_js = Vec::new();

    for ext in &extensions {
        for file in ext.lazy_loaded_esm_files.iter() {
            if !consumed.contains(file.specifier)
                && let Ok(source) = file.load()
            {
                let source = maybe_transpile(file.specifier, &source);
                residual_esm.push((file.specifier, source));
            }
        }
        for file in ext.lazy_loaded_js_files.iter() {
            if !consumed.contains(file.specifier)
                && let Ok(source) = file.load()
            {
                let source = maybe_transpile(file.specifier, &source);
                residual_js.push((file.specifier, source));
            }
        }
    }

    println!("Residual lazy sources: {} ESM, {} JS", residual_esm.len(), residual_js.len());

    let mut generated = String::new();
    write_line(&mut generated, "// Auto-generated by tools/snapshot - do not edit");
    write_line(
        &mut generated,
        "// Residual lazy-loaded sources not consumed during snapshot creation\n",
    );

    write_line(&mut generated, "pub static RESIDUAL_LAZY_ESM_SOURCES: &[(&str, &str)] = &[");
    for (specifier, source) in &residual_esm {
        let escaped = escape_for_raw_string(source);
        write_line(&mut generated, &format!("    (\"{specifier}\", r###\"{escaped}\"###),"));
    }
    write_line(&mut generated, "];\n");

    write_line(&mut generated, "pub static RESIDUAL_LAZY_JS_SOURCES: &[(&str, &str)] = &[");
    for (specifier, source) in &residual_js {
        let escaped = escape_for_raw_string(source);
        write_line(&mut generated, &format!("    (\"{specifier}\", r###\"{escaped}\"###),"));
    }
    write_line(&mut generated, "];");

    std::fs::write(&residual_path, &generated).expect("Failed to write residual sources");
    println!("Residual sources written to {}", residual_path.display());
    println!("Files loaded during snapshot: {}", output.files_loaded_during_snapshot.len());
}

fn write_line(buf: &mut String, line: &str) {
    writeln!(buf, "{line}").expect("Failed to write to string buffer");
}

fn maybe_transpile(specifier: &str, source: &str) -> String {
    use deno_ast::MediaType;
    use std::path::Path;

    let media_type = if specifier.starts_with("node:") {
        MediaType::TypeScript
    } else {
        MediaType::from_path(Path::new(specifier))
    };

    match media_type {
        MediaType::TypeScript | MediaType::Tsx | MediaType::Jsx => {}
        _ => return source.to_string(),
    }

    let specifier_url = url::Url::parse(specifier).unwrap_or_else(|_| {
        url::Url::parse(&format!("file:///{specifier}")).expect("invalid specifier")
    });

    let parsed = deno_ast::parse_module(deno_ast::ParseParams {
        specifier: specifier_url,
        text: source.into(),
        media_type,
        capture_tokens: false,
        scope_analysis: false,
        maybe_syntax: None,
    })
    .unwrap_or_else(|e| panic!("Failed to parse '{specifier}': {e}"));

    parsed
        .transpile(
            &deno_ast::TranspileOptions {
                imports_not_used_as_values: deno_ast::ImportsNotUsedAsValues::Remove,
                ..Default::default()
            },
            &deno_ast::TranspileModuleOptions::default(),
            &deno_ast::EmitOptions {
                source_map: deno_ast::SourceMapOption::None,
                ..Default::default()
            },
        )
        .unwrap_or_else(|e| panic!("Failed to transpile '{specifier}': {e}"))
        .into_source()
        .text
}

#[allow(clippy::disallowed_methods)]
fn escape_for_raw_string(s: &str) -> String {
    s.replace("\"###", "\"####")
}
