import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const REFRESH_RUNTIME_SOURCE_PATH = 'packages/common/refresh-runtime.js'
const REFRESH_RUNTIME_URL = `https://raw.githubusercontent.com/vitejs/vite-plugin-react/main/${REFRESH_RUNTIME_SOURCE_PATH}`
const README_URL = 'https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react'

const FETCH_TIMEOUT_MS = 30_000

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const outPath = path.join(root, 'src/vite/transform/react-refresh-runtime.ts')

const GENERATED_FILE_BANNER = [
  '/**',
  ' * @generated by `pnpm --filter rari update-react-refresh-runtime`',
  ' * Do not edit this file manually.',
  ` * Source: ${REFRESH_RUNTIME_URL}`,
  ' */',
].join('\n')

let response: Response
try {
  response = await fetch(REFRESH_RUNTIME_URL, {
    headers: { 'User-Agent': 'rari-update-react-refresh-runtime' },
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
  })
} catch (error) {
  const timedOut =
    error instanceof Error && (error.name === 'TimeoutError' || error.name === 'AbortError')
  if (timedOut) {
    throw new Error(
      `Timed out fetching React Refresh runtime from ${REFRESH_RUNTIME_URL} after ${FETCH_TIMEOUT_MS}ms`,
    )
  }
  throw error
}

if (!response.ok) {
  throw new Error(
    `Failed to fetch React Refresh runtime: ${response.status} ${response.statusText}`,
  )
}

const runtimeSource = (await response.text()).replaceAll('__README_URL__', README_URL)
if (!runtimeSource.includes('injectIntoGlobalHook')) {
  throw new Error(
    `Unexpected React Refresh runtime payload from ${REFRESH_RUNTIME_URL} (missing injectIntoGlobalHook)`,
  )
}

const out = `${GENERATED_FILE_BANNER}
export const REACT_REFRESH_RUNTIME_CODE = ${JSON.stringify(runtimeSource)}
`

fs.writeFileSync(outPath, out)

console.log(
  `Updated React Refresh runtime (${runtimeSource.length} chars) -> ${path.relative(root, outPath)}`,
)
