import { spawnSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const FONT_METADATA_URL = 'https://fonts.google.com/metadata/fonts'

interface GoogleFamilyMeta {
  readonly family: string
}

interface GoogleFontsMetadata {
  readonly familyMetadataList: readonly GoogleFamilyMeta[]
}

interface NormalizedFamily {
  readonly family: string
  readonly exportName: string
}

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const googlePath = path.join(root, 'src/font/google.ts')

const GENERATED_FILE_BANNER = [
  '/**',
  ' * @generated by `pnpm --filter rari update-google-fonts`',
  ' * Do not edit this file manually.',
  ` * Source: ${FONT_METADATA_URL}`,
  ' */',
].join('\n')

const TS_RESERVED = new Set([
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'else',
  'enum',
  'export',
  'extends',
  'false',
  'finally',
  'for',
  'function',
  'if',
  'import',
  'in',
  'instanceof',
  'new',
  'null',
  'return',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'typeof',
  'var',
  'void',
  'while',
  'with',
  'yield',
  'let',
  'static',
  'implements',
  'interface',
  'package',
  'private',
  'protected',
  'public',
  'await',
  'async',
  'of',
  'as',
  'from',
  'type',
])

function toExportName(family: string): string {
  const exportName = family.replaceAll(' ', '_')
  if (!/^[a-z_$][\w$]*$/i.test(exportName) || TS_RESERVED.has(exportName)) {
    throw new Error(
      `Google font family ${JSON.stringify(family)} normalizes to invalid TypeScript export name ${JSON.stringify(exportName)}`,
    )
  }
  return exportName
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value != null && typeof value === 'object' && !Array.isArray(value)
}

function isGoogleFamilyMeta(value: unknown): value is GoogleFamilyMeta {
  return isRecord(value) && typeof value.family === 'string' && value.family !== ''
}

function isGoogleFontsMetadata(value: unknown): value is GoogleFontsMetadata {
  if (!isRecord(value) || !Array.isArray(value.familyMetadataList)) return false
  return value.familyMetadataList.every(entry => isGoogleFamilyMeta(entry))
}

function parseMetadataPayload(raw: string): unknown {
  const text = raw.replace(/^\)\]\}'\n?/, '')
  return JSON.parse(text) as unknown
}

function normalizeFamily(entry: GoogleFamilyMeta): NormalizedFamily {
  return {
    family: entry.family,
    exportName: toExportName(entry.family),
  }
}

const METADATA_FETCH_TIMEOUT_MS = 30_000

let response: Response
try {
  response = await fetch(FONT_METADATA_URL, {
    headers: { 'User-Agent': 'rari-update-google-fonts' },
    signal: AbortSignal.timeout(METADATA_FETCH_TIMEOUT_MS),
  })
} catch (error) {
  const timedOut =
    error instanceof Error && (error.name === 'TimeoutError' || error.name === 'AbortError')
  if (timedOut) {
    throw new Error(
      `Timed out fetching Google font metadata from ${FONT_METADATA_URL} after ${METADATA_FETCH_TIMEOUT_MS}ms`,
    )
  }
  throw error
}
if (!response.ok) {
  throw new Error(`Failed to fetch font metadata: ${response.status} ${response.statusText}`)
}

const raw = parseMetadataPayload(await response.text())
if (!isGoogleFontsMetadata(raw)) {
  throw new Error('Unexpected fonts.google.com/metadata/fonts shape')
}

const byExport = new Map<string, NormalizedFamily>()
for (const entry of raw.familyMetadataList) {
  const normalized = normalizeFamily(entry)
  const existing = byExport.get(normalized.exportName)
  if (existing != null && existing.family !== normalized.family) {
    throw new Error(
      `Duplicate Google font export name ${JSON.stringify(normalized.exportName)} for families ${JSON.stringify(existing.family)} and ${JSON.stringify(normalized.family)}`,
    )
  }
  byExport.set(normalized.exportName, normalized)
}

const families = [...byExport.values()].sort((a, b) => a.family.localeCompare(b.family))

const googleOut: string[] = []
googleOut.push(GENERATED_FILE_BANNER)
googleOut.push("import type { Font, GoogleFontOptions } from './types'")
googleOut.push('')
googleOut.push('export type GoogleFontFn = (options?: GoogleFontOptions) => Font')
googleOut.push('')
googleOut.push('const googleFontStub: GoogleFontFn = function googleFont(')
googleOut.push('  _options: GoogleFontOptions = {},')
googleOut.push('): Font {')
googleOut.push('  throw new Error(')
googleOut.push(
  "    'Google font imports from `rari/font/google` must be compiled by the rari Vite plugin. Add `rari()` to your Vite config, and pass a static options object.',",
)
googleOut.push('  )')
googleOut.push('}')
googleOut.push('')

for (const family of families) {
  googleOut.push(`export const ${family.exportName}: GoogleFontFn = googleFontStub`)
}

googleOut.push('')
googleOut.push("export type { Font, FontDisplay, GoogleFontOptions } from './types'")
googleOut.push('')

fs.writeFileSync(googlePath, googleOut.join('\n'))

const formatTargets = [path.relative(root, googlePath)]
const format = spawnSync('pnpm', ['exec', 'vp', 'fmt', ...formatTargets], {
  cwd: root,
  encoding: 'utf8',
})
if (format.status !== 0) {
  throw new Error(
    `Failed to format generated Google font files:\n${format.stderr || format.stdout || `exit ${format.status}`}`,
  )
}

console.log(`Updated ${families.length} Google fonts -> ${formatTargets.join(' + ')}`)
