import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import {
  collectViteEnvKeys,
  emitRariEnvTypes,
  parseViteEnvKeysFromSource,
  rariEnvDtsPath,
  renderEnvDts,
} from '@rari/vite/env-types'
import { afterEach, describe, expect, it } from 'vite-plus/test'

describe('env-types', () => {
  const tempDirs: string[] = []

  afterEach(() => {
    for (const dir of tempDirs.splice(0)) {
      fs.rmSync(dir, { recursive: true, force: true })
    }
  })

  function makeTempProject(): string {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'rari-env-types-'))
    tempDirs.push(dir)
    return dir
  }

  it('parses VITE_* keys from dotenv source', () => {
    expect(
      parseViteEnvKeysFromSource(`
# comment
VITE_A=1
export VITE_B=2
NOT_VITE=3
VITE_incomplete
    `),
    ).toEqual(['VITE_A', 'VITE_B'])
  })

  it('renders ImportMetaEnv ambient declarations', () => {
    expect(renderEnvDts(['VITE_A', 'VITE_B'])).toBe(`// Generated by rari. Do not edit.
interface ImportMetaEnv {
  readonly VITE_A?: string
  readonly VITE_B?: string
}
`)
  })

  it('emits env.d.ts under node_modules/.rari/types from .env.example', () => {
    const root = makeTempProject()
    fs.writeFileSync(
      path.join(root, '.env.example'),
      'VITE_POSTHOG_KEY=\nVITE_SENTRY_DSN=https://example\n',
    )

    const outFile = emitRariEnvTypes(root, 'development')
    expect(outFile).toBe(rariEnvDtsPath(root))
    expect(fs.readFileSync(outFile, 'utf8')).toContain('readonly VITE_POSTHOG_KEY?: string')
    expect(fs.readFileSync(outFile, 'utf8')).toContain('readonly VITE_SENTRY_DSN?: string')
    expect(collectViteEnvKeys(root, 'development')).toEqual(['VITE_POSTHOG_KEY', 'VITE_SENTRY_DSN'])
  })

  it('skips rewriting when content is unchanged', () => {
    const root = makeTempProject()
    fs.writeFileSync(path.join(root, '.env'), 'VITE_ONLY=1\n')
    const first = emitRariEnvTypes(root, 'development')
    const before = fs.statSync(first).mtimeMs
    emitRariEnvTypes(root, 'development')
    expect(fs.statSync(first).mtimeMs).toBe(before)
  })
})
