name: CodSpeed

on:
  push:
    branches:
      - main
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # for OpenID Connect authentication with CodSpeed
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: nightly

      - uses: ./.github/actions/setup-rust-build-deps

      - name: Install cargo-codspeed
        run: cargo install cargo-codspeed --locked

      - name: Build the benchmarks
        run: cargo codspeed build -p rari_use_cache

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@0ca9cbbf4623b599a6c3ed4fc8a922942705d9f1 # v5.0.2
        with:
          mode: simulation
          run: cargo codspeed run -p rari_use_cache
